import '@/app/globals.css'
import { Toaster } from 'sonner';


export const metadata = {
  title: 'Galería de imágenes',
  description: 'Generated by create next app',
  manifest: '/manifest.json'
}

export default async function RootLayout({ children }) {

  return (
    <html lang="es">
      <body className={`antialiased`}  >
        {children}
        <Toaster position="top-right" richColors />
      </body>
    </html>
  )
}